spring:
data:
mongodb:
uri: mongodb+srv://singhmanonit50_db_user:0HCpOfTpUoxuT2fj@cluster4.kn8ukkm.mongodb.net/?appName=Cluster4
database: journaldb

server:
port: 8080
servlet:
context-path: /journal