spring.application.name=journalApp

spring.data.mongodb.uri=mongodb+srv://singhmanonit50_db_user:0HCpOfTpUoxuT2fj@cluster4.kn8ukkm.mongodb.net/?appName=Cluster4

spring.data.mongodb.auto-index-creation=true